apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: biostechnologyng@gmail.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx


#1.  Install Cert-Manager (If Not Installed)
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml

# 2. Verify Cert Manager 
# kubectl get pods -n cert-manager

# 3. Apply this yml file
# kubectl apply -f cluster-issuer.yaml

# 4. apply my production ingress
# kubectl apply -f ingress.yml

# 5. Verify SSL Certificate: Check if the TLS certificate is issued: 
# kubectl get certificate
# kubectl describe certificate lendora-tls

# 6. If there are errors, check Cert-Manager logs:
# kubectl logs -n cert-manager -l app.kubernetes.io/name=cert-manager

# 7.  Test HTTPS Access
# curl -IL http://api.lendora.ng
