apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-service
  labels:
    app: broker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-service
  template:
    metadata:
      labels:
        app: broker-service
    spec:
      initContainers:
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z redis 6379; do echo Waiting for Redis; sleep 2; done;']
      containers:
      - name: broker-service
        image: "biostech/rental-broker-service:1.0.0"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_URL
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: INVENTORY_SERVICE_URL
        - name: AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_URL
        - name: MAIL_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MAIL_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: broker-service
  labels:
    app: broker-service
spec:
  ports:
    - protocol: TCP
      name: main-port
      port: 8080
      targetPort: 8080
  selector:
    app: broker-service
