apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  REDIS_URL: "redis"
  #DATABASE CONFIG Starts here------#
  DATABASE_NAME: "rental_solution_db"
  DATABASE_TYPE: "postgres"
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_USER: "admin"
  DATABASE_PASSWORD: "password"
  DATABASE_SSLMODE: "disable"
  DATABASE_TIMEZONE: "UTC"
  DATABASE_CONNECT_TIMEOUT: "5"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "rental_solution_db"
  POSTGRES_PORT: "5432"
  PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  PGADMIN_DEFAULT_PASSWORD: "admin"
  #MAIL CONFIG HERE-------------#
  MAIL_DOMAIN: localhost
  MAIL_HOST: mailhog
  MAIL_PORT: "1025"
  MAIL_ENCRYPTION: none
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  FROM_NAME: RentalService
  FROM_ADDRESS: support@rentals.com
  #JWT AUTH CONFIGS----------------------#
  JWT_SECRET: "6trtyf644fud4ryfduiq@5483743"
  JWT_EXPIRATION_TIME: "3600"
  JWT_VERIFICATION_TOKEN_EXPIRATION_TIME: "21600"
  # RABBIT MQ CONFIGS
  RABBITMQ_USER: "user"
  RABBITMQ_PASSWORD: "password"
  RABBITMQ_HOST: "localhost:5672"
  RABBITMQ_URL: "amqp://user:password@rabbitmq:5672 "
  # INTERNAL SERVICE URLS CONFIG
  ROOT_URL: "http://localhost:8080/#api/v1/authentication/verify-email"




# ROOT_URL=http://localhost:8080/api/v1/authentication/verify-email
# AUTH_URL=http://authentication/api/v1/authentication/
# MAIL_URL=http://mail-service/
# LOGGER_URL=http://logging-service/log
# AUTH_SERVICE_URL=http://authentication/api/v1/
# LISTENER_SERVICE_URL=http://listener-service/api/v1/
# LOGGING_SERVICE_URL=http://logging-service/api/v1/
# MAIL_SERVICE_URL=http://mail-service/api/v1/
# INVENTORY_SERVICE_URL=http://inventory-service/api/v1/
# PORT=8080
# RABBITMQ_USER=user
# RABBITMQ_PASSWORD=password
# RABBITMQ_HOST=localhost:5672
# RABBITMQ_URL=amqp://user:password@rabbitmq:5672