apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: "biostech/rental-inventory-service:1.0.0"
          imagePullPolicy: Always # Forces Kubernetes to pull every time
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_PORT
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_NAME
            - name: DATABASE_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_SSLMODE
            - name: DATABASE_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_TIMEZONE
            - name: DATABASE_CONNECT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_CONNECT_TIMEOUT
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CLOUDINARY_API_SECRET
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
