apiVersion: apps/v1
kind: Deployment
metadata: 
  name: listener-service
  labels:
    app: listener-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener-service
  template:
    metadata:
      labels:
        app: listener-service
    spec:
      containers:
      - name: listener-service
        image: "biostech/rental-listener-service:1.0.0"
        ports:
        - containerPort: 80                # Internal port 80 as per docker-compose config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: listener-service
  labels:
    app: listener-service
spec:
  type: ClusterIP              # Only accessible within the cluster
  selector:
    app: listener-service
  ports:
    - protocol: TCP
      port: 80                 # Cluster-internal port
      targetPort: 80            # Mail service's container port
