apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-ui
  labels:
    app: redis-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-ui
  template:
    metadata:
      labels:
        app: redis-ui
    spec:
      containers:
      - name: redis-ui
        image: rediscommander/redis-commander:latest
        env:
        - name: REDIS_HOSTS
          value: "redis"
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: redis-ui
  labels:
    app: redis-ui
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: redis-ui
