apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
  labels:
    app: subscription-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
        - name: authentication-service
          image: "biostech/rental-subscription-service:1.0.0"
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_PORT
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_NAME
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_URL
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_URL
            - name: ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ROOT_URL
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  labels:
    app: subscription-service
spec:
  type: ClusterIP # Only accessible within the cluster
  selector:
    app: subscription-service
  ports:
    - protocol: TCP
      port: 80 # Cluster-internal port
      targetPort: 80 # Mail service's container port
